### ISSUE TITLE
the big release todo

### ISSUE THREAD

**Issue by ix0rai** [ix0rai/tantalisingteas#2]
#### drinkable tea items:
- [x] colour based on ingredients
- [x] variable transparency based on strength
- [x] dynamically updated whenever ingredients change

#### tea cauldron
- [ ] animation of placed ingredient fading into cauldron
- [ ] dynamic colour with crossfade
- [ ] boiling effect (reference: minecraft 1.18 trailer water effects)

#### misc
- [x] automatic asset generation

#### tea cauldron
- [x] steeping
- [x] storing ingredient data
- [x] works with everything in tea ingredient tag
- [x] insertion and removal
- [x] boiling
- [ ] still tea cauldron (non-boiling cauldron that has tea in it)

#### tea receptacles
- [x] storing all necessary data
- [x] custom stack names
- [ ] dynamic food components
- [ ] automatic data updating

#### content
- [ ] various tea ingredients (different kinds of tea leaves, different spices, berries, etc)
- [ ] teacups
- [ ] teapots
- [ ] mugs
- [ ] decorative items

**Comment by ix0rai** [comment]
all of this is now listed in https://github.com/users/ix0rai/projects/3/views/1
